coins_all = ['BNB/USDT', 'DOGE/USDT',
             'SOL/USDT', 'TRX/USDT', 'ETH/USDT',
             'LINK/USDT', 'DOT/USDT', 'AVAX/USDT',
             'MATIC/USDT', 'XRP/USDT', 'BTC/USDT',
             'NEAR/USDT', 'ALGO/USDT', 'DASH/USDT',
             'ADA/USDT', 'UNI/USDT', 'LTC/USDT', 'ATOM/USDT', 'ETC/USDT', 'FTT/USDT',
             'XMR/USDT', 'COMP/USDT', 'XLM/USDT', 'BCH/USDT', 'VET/USDT', 'FLOWUSDT',
             'CHZ/USDT', 'LUNC/USDT', 'APE/USDT', 'APT/USDT', 'HBAR/USDT', 'EGLD/USDT',
             'SAND/USDT', 'MANA/USDT', 'LUNA/USDT', 'FTM/USDT', 'NEO/USDT', 'ENJ/USDT']

coins_bybit = ['BNB/USDT:USDT', 'DOGE/USDT:USDT',
             'SOL/USDT:USDT', 'TRX/USDT:USDT', 'ETH/USDT:USDT',
             'LINK/USDT:USDT', 'DOT/USDT:USDT', 'AVAX/USDT:USDT',
             'MATIC/USDT:USDT', 'XRP/USDT:USDT', 'BTC/USDT:USDT',
             'NEAR/USDT:USDT', 'ALGO/USDT:USDT', 'DASH/USDT:USDT',
               'ADA/USDT:USDT', 'UNI/USDT:USDT', 'LTC/USDT:USDT', 'ATOM/USDT:USDT', 'ETC/USDT:USDT', 'FTT/USDT:USDT',
               'XMR/USDT:USDT', 'COMP/USDT:USDT', 'XLM/USDT:USDT', 'BCH/USDT:USDT', 'VET/USDT:USDT', 'FLOWUSDT:USDT',
               'CHZ/USDT:USDT', 'LUNC/USDT:USDT', 'APE/USDT:USDT', 'APT/USDT:USDT', 'HBAR/USDT:USDT', 'EGLD/USDT:USDT',
               'SAND/USDT:USDT', 'MANA/USDT:USDT', 'LUNA/USDT:USDT', 'FTM/USDT:USDT', 'NEO/USDT:USDT', 'ENJ/USDT:USDT'
               ]

coins = ['BNBUSDT', 'DOGEUSDT',
             'SOLUSDT', 'TRXUSDT', 'ETHUSDT',
             'LINKUSDT', 'DOTUSDT', 'AVAXUSDT',
             'MATICUSDT', 'XRPUSDT', 'BTCUSDT',
             'NEARUSDT', 'ALGOUSDT', 'DASHUSDT',
         'ADAUSDT', 'UNIUSDT', 'LTCUSDT', 'ATOMUSDT', 'ETCUSDT', 'FTTUSDT',
         'XMRUSDT', 'COMPUSDT', 'XLMUSDT', 'BCHUSDT', 'VETUSDT', 'FLOWUSDT',
         'CHZUSDT', 'LUNCUSDT', 'APEUSDT', 'APTUSDT', 'HBARUSDT', 'EGLDUSDT',
         'SANDUSDT', 'MANAUSDT', 'LUNAUSDT', 'FTMUSDT', 'NEOUSDT', 'ENJUSDT']
